export const typographys = {
  headline: {
    fontFamily: "PhilsonBlock",
    fontWeight: 400,
    fontSize: "28px",
    lineHeight: "48px",
    letterSpacing: "-0.06em",
    WebkitTextStroke: "1.5px #1A1A1A",
  },
  "headline-1": {
    fontFamily: "JetBrainsMono",
    fontWeight: 600,
    fontSize: "24px",
    lineHeight: "32px",
    letterSpacing: "-0.02em",
  },
  "headline-2": {
    fontFamily: "JetBrainsMono",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "24px",
    letterSpacing: "-0.02em",
  },
  "headline-3": {
    fontFamily: "JetBrainsMono",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "20px",
    letterSpacing: "-0.02em",
  },
  "paragraph-1": {
    fontFamily: "JetBrainsMono",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "24px",
    letterSpacing: "-0.02em",
  },
  "paragraph-2": {
    fontFamily: "JetBrainsMono",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "20px",
    letterSpacing: "-0.02em",
    fontFeatureSettings: "'liga' off",
  },
  "paragraph-3": {
    fontFamily: "JetBrainsMono",
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "-0.02em",
    fontFeatureSettings: "'liga' off",
  },
  "button-1": {
    fontFamily: "PhilsonBlock",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "16px",
    fontFeatureSettings: "'ss01' on, 'liga' off",
    WebkitTextStroke: "1px #1A1A1A",
    textShadow: "3px 3px 0px rgba(13, 13, 13, 0.1)",
  },
  "button-2": {
    fontFamily: "JetBrainsMono",
    fontWeight: 700,
    fontSize: "14px",
    lineHeight: "16px",
    letterSpacing: "-0.02em",
  },
  "label-1": {
    fontFamily: "JetBrainsMono",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "16px",
    letterSpacing: "-0.02em",
  },
  "label-2": {
    fontFamily: "JetBrainsMono",
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "-0.02em",
  },
};
