import axios from "axios";
import {
  FREE_OBJECT_CONTRACT_ADDRESS,
  QUEST_OBJECT_CONTRACT_ADDRESS,
  PREMIUM_OBJECT_CONTRACT_ADDRESS,
  WALLPAPER_CONTRACT_ADDRESS,
} from "~/constants";
import { ObjectContractAddress, WallpaperContractAddress } from ".";

export type ObjectMetadata = {
  tokenId: number;
  name: string;
  image_url: string;
  json_url: string;
  size: [number, number, number] | [number, number];
  creator: string;
  maxClaimed: number;
  price: number;
  EXP?: number;
  relatedProject?: string;
};

export const objectMetadataList: { [contract in ObjectContractAddress | WallpaperContractAddress]: { [tokenId: number]: ObjectMetadata } } =
  {
    [QUEST_OBJECT_CONTRACT_ADDRESS]: {
      1: {
        tokenId: 1,
        name: "ENS Signboard",
        image_url: "https://www.arweave.net/URXxpvG0RgwXDqp0RUMB5fTZjWSL4On8UtLDB4wxqWY?ext=png",
        json_url: "https://www.arweave.net/3deIUCeVoPU0Esc-6juFAlF8hwrMxn21b37-9Rv7D64",
        size: [1, 1, 2],
        relatedProject: "ENS",
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
        EXP: 100,
      },
      3: {
        tokenId: 3,
        name: "ETH Motorbike",
        image_url: "https://www.arweave.net/_p6Wu3p6t4sHEpAaCeJ7Xsv6peaLZj_AP1avuTbGD5s?ext=png",
        json_url: "https://www.arweave.net/MbDvcxNKUvhAB9QEiuQWozIlxnYX4xCJsgBxw0aqi_4",
        size: [1, 1, 1],
        relatedProject: "Ethereum",
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
        EXP: 1000,
      },
      4: {
        tokenId: 4,
        name: "ETH People",
        image_url: "https://www.arweave.net/pj2CzgZF1sLaziKZRAoKxkjgnRqX7BW7r43uPOltj1g?ext=png",
        json_url: "https://www.arweave.net/AR_NtoSZhfCjxeCf8mj1QQdWfIghDYUWOmtBqwmh3C4",
        size: [1, 1, 1],
        relatedProject: "Ethereum",
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
        EXP: 5000,
      },
      5: {
        tokenId: 5,
        name: "ETH Truck",
        image_url: "https://www.arweave.net/y-lXYFoMzL_GI6xLzPtXMNMUslzaRVr9d7qvA5rMzMw?ext=png",
        json_url: "https://www.arweave.net/O8Vz0_flHLkwzq0nxPaSPp_NoPtMQnrpt6u2c6ZwNvk",
        size: [1, 2, 1],
        relatedProject: "Ethereum",
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
        EXP: 10000,
      },
      6: {
        tokenId: 6,
        name: "ETH Building",
        image_url: "https://www.arweave.net/JMbEd3llRHJHW21wXMrfBh07RaluHZDC1nYPvbyhq9s?ext=png",
        json_url: "https://www.arweave.net/aD0e1vKYOUImE3EsYfpTsS764H4k5Q1i57H5fX_JfQ8",
        size: [3, 3, 4],
        relatedProject: "Ethereum",
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
        EXP: 50000,
      },
      7: {
        tokenId: 7,
        name: "USDC Seesaw",
        image_url: "https://www.arweave.net/PNcEUuHyl0pi7xPS5KdvGo0RiCBpSfKzLexua9IZdm8?ext=png",
        json_url: "https://www.arweave.net/xs-qNkISw7dRn9eWehXn1HvrdUWs9NvSVCYGb64_00A",
        size: [1, 2, 2],
        relatedProject: "USDC",
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
        EXP: 100,
      },
      8: {
        tokenId: 8,
        name: "USDC Card Tower",
        image_url: "https://www.arweave.net/AEJagG11Z6sFgApxZCEapOdlCjl791f0ObUUQO8EDzY?ext=png",
        json_url: "https://www.arweave.net/3WAdj5AIqeLGUhfHar97jwGVIlmyapPDetvKcrYahlM",
        size: [2, 2, 5],
        relatedProject: "USDC",
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
        EXP: 1000,
      },
      10: {
        tokenId: 10,
        name: "Uniswap Chess Piece",
        image_url: "https://www.arweave.net/aAMatQxpC1dk7S-mGJO6mS5xgnaSd3Z8thD6PtxzgSA?ext=png",
        json_url: "https://www.arweave.net/20mXDC_BdzEJsuIjnSS2XBscBOXTjWU_VGRUJ0SiLi4",
        size: [1, 1, 2],
        relatedProject: "Uniswap",
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
        EXP: 200,
      },
      11: {
        tokenId: 11,
        name: "Uniswap Motorbike",
        image_url: "https://www.arweave.net/BEhkFy9VxB71j5AfcsRLBqqEZ60ms36K6XxUojIeqBU?ext=png",
        json_url: "https://www.arweave.net/sgz1gI7NFXHYlb2gjNFSNZtYDFYcRBz3LYBSRdvi-HQ",
        size: [1, 2, 1],
        relatedProject: "Uniswap",
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
        EXP: 1000,
      },
      12: {
        tokenId: 12,
        name: "Uniswap Building",
        image_url: "https://www.arweave.net/hOecaTbVogfeBcgfjLjcG_9_fR7TWe4ism8Pm6whTTg?ext=png",
        json_url: "https://www.arweave.net/pjw7ot24MlVgc5h2Gf-5Y_ijeSw_s6CZXr_01fa6Q8I",
        size: [2, 2, 6],
        relatedProject: "Uniswap",
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
        EXP: 2000,
      },
      14: {
        tokenId: 14,
        name: "DAI Pool",
        image_url: "https://www.arweave.net/IDEXeDI8-39N0dw8ciOogNlzpGX9jvXKQLxvZhJOgzI?ext=png",
        json_url: "https://www.arweave.net/kyNXvwK8ve8Ro7xPQ3MtI2QTLzKt2s7nfK7ats5zOQk",
        size: [1, 1, 1],
        relatedProject: "Uniswap",
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
        EXP: 200,
      },
      15: {
        tokenId: 15,
        name: "DAI Car",
        image_url: "https://www.arweave.net/f_9-CmfyRfvl9mH_-uNQOpJAHuXG_ZsaK3IGK-NP-eM?ext=png",
        json_url: "https://www.arweave.net/zQpAPn6GX6WgrX_uyMYfiknz1NLqs-_uiKAL4rmPReI",
        size: [1, 2, 1],
        relatedProject: "Uniswap",
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
        EXP: 2000,
      },
      25: {
        tokenId: 25,
        name: "Developer Prefab",
        image_url: "https://www.arweave.net/rZ3SBUgxZYLOd7l8mPVqt5PnhHoLjRmcy5keGUfwxSc?ext=png",
        json_url: "https://www.arweave.net/ZDQ7mKG9P0DcUxf9A5eJvDNl-ENAdrDNdbvkTJfQFb4",
        size: [2, 2, 4],
        relatedProject: "Ethereum",
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
        EXP: 5000,
      },
      37: {
        tokenId: 37,
        name: "PHI Chess Piece",
        image_url: "https://www.arweave.net/NOEgYlRlSnQ--KU4O6Ng99rp1pXwRpE9z30bI0Kkr6c?ext=png",
        json_url: "https://www.arweave.net/yr4fkHkow1Tqsu24E941_9l5e1hHbk-h0jEKiX6dbUA",
        size: [1, 1, 2],
        relatedProject: "PHI",
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
        EXP: 100,
      },
      38: {
        tokenId: 38,
        name: "PHI LogoBuildings",
        image_url: "https://www.arweave.net/OWXMy9TKkzJxTpwqpsmynZnHfCRml-Km_2_jRcmPGN8?ext=png",
        json_url: "https://www.arweave.net/8tCQLFSEyQbfJ-wpNr4OBaZsC8BrU5Bqq5gNcDn2w6s",
        size: [1, 2, 2],
        relatedProject: "PHI",
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
        EXP: 500,
      },
      39: {
        tokenId: 39,
        name: "PHI Billboard",
        image_url: "https://www.arweave.net/bgAaP5OAwtl4gbpHInlKluQeh6wHMdHDyzqMui7Jm5o?ext=png",
        json_url: "https://www.arweave.net/fKWxcyZ7x94lrXhb1ZGzHHB9fB7Jiw_LyVjChgqJMrQ",
        size: [1, 3, 3],
        relatedProject: "PHI",
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
        EXP: 1000,
      },
      40: {
        tokenId: 40,
        name: "PHI Building Blockbob",
        image_url: "https://www.arweave.net/KxhEGGpGQA-VtX1Uy9yRIIZoHc3IM523_R1uB82xMgg?ext=png",
        json_url: "https://www.arweave.net/WV1IjntxosGhdjuuQM2ik2WLc3o98qHkVg0BbeckUrQ",
        size: [2, 1, 5],
        relatedProject: "PHI",
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
        EXP: 5000,
      },
      41: {
        tokenId: 41,
        name: "PHI Building",
        image_url: "https://www.arweave.net/7uxU8ffa3YvCIhRM1cIc2bzB1FfdNELde9-OB65Fgf4?ext=png",
        json_url: "https://www.arweave.net/La23Ae8Dw71bdsdzbuxWtwSRNZ28ilcxHnkjukRJJDY",
        size: [2, 1, 5],
        relatedProject: "PHI",
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
        EXP: 10000,
      },
      46: {
        tokenId: 46,
        name: "PHI Monument",
        image_url: "https://www.arweave.net/1y5qHBd5PnQepAwmZowpTPx_rCbMvXZAaMPvOV5wtyk?ext=png",
        json_url: "https://www.arweave.net/IL8zfvLUjmOU-C6Ralc550oaWwTllfCn6CTTkL9d-_s",
        size: [1, 2, 2],
        relatedProject: "StarkNet",
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
        EXP: 1000,
      },
    },
    [FREE_OBJECT_CONTRACT_ADDRESS]: {
      1: {
        tokenId: 1,
        name: "Twitter Tree",
        image_url: "https://www.arweave.net/l1zXahCUNqIRojyAvVw-yNUSwbmHkLTx9mMm59teGiE?ext=png",
        json_url: "https://www.arweave.net/x6q6HpCxWXI0GU4CDQ9WoZJDH5GBD1BkZfVcV-KJxQk",
        size: [1, 1, 2],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
      },
      2: {
        tokenId: 2,
        name: "Discord Monument",
        image_url: "https://www.arweave.net/huoSybbxTA3zAlfLXZZkb-r6GG3zJXJTuUNao9og5fk?ext=png",
        json_url: "https://www.arweave.net/ptYzUVmQFMIOIVWQGQRWjBjAfY3EbK3FnJxK6e6y8U8",
        size: [1, 1, 1],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
      },
      3: {
        tokenId: 3,
        name: "Github Display",
        image_url: "https://www.arweave.net/EZawXgJXnU6SPR7ehg5OI1_8gRyNjMUdpR6pd905NpY?ext=png",
        json_url: "https://www.arweave.net/YRq_nRDao80DxUaONnc9wgppnS2zlZZAgajJAJusmak",
        size: [1, 1, 2],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
      },
      4: {
        tokenId: 4,
        name: "HardHat Group 1",
        image_url: "https://www.arweave.net/xPF2NpI6EHsAeYDsl3xhcqvGX6f2HknZjkTBwJgj39o?ext=png",
        json_url: "https://www.arweave.net/nhb8jqU2PpfagrzIOukD5hrqPKr59_aecNyLQkO5O7w",
        size: [2, 2, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      5: {
        tokenId: 5,
        name: "Puddle",
        image_url: "https://www.arweave.net/rgyS1g3-5AwWBD3deRJGEwxMnN1QLBpT-Mh6-hRLj5o?ext=png",
        json_url: "https://www.arweave.net/VOTfZHecsl_ffNiErlo2YNgPO03p9hziUle0806az4o",
        size: [2, 2, 1],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
      },
      6: {
        tokenId: 6,
        name: "Container Set 1",
        image_url: "https://www.arweave.net/a6d5ENAleCOlNk4Sv4zf6k4EZK6iuJdjEFuhQAiaXw4?ext=png",
        json_url: "https://www.arweave.net/BqL1jKp21t1qC3dYBAJpJws3iCAmRx6li1Wt0MfFJaw",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      7: {
        tokenId: 7,
        name: "Container Set 2",
        image_url: "https://www.arweave.net/N-x2Xtkcoy6e9wYdjoDPDCBnc70ytwynZ_uoIQhqUcs?ext=png",
        json_url: "https://www.arweave.net/bH7C1k2ACSOZGY3KsrggkHKj-XTru99AvkaOCNJRNHw",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      8: {
        tokenId: 8,
        name: "Container Set 3",
        image_url: "https://www.arweave.net/TilRkEjR2VcS4Ri1HoKKhagNGRoWHh2c-PIuxxWHjiY?ext=png",
        json_url: "https://www.arweave.net/tJhGAgBjhAFLNORhisni23BwVtUqZvBR2kLUNShRy2k",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      9: {
        tokenId: 9,
        name: "House A",
        image_url: "https://www.arweave.net/595bUmeMekiTihqS0tW1OjZtwWk1PBWlCbKvUAgqLug?ext=png",
        json_url: "https://www.arweave.net/SNiETEx_rVn1TG_Q2RbTi8-A14-vOYrfnb-9jtnKPGI",
        size: [2, 3, 3],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      10: {
        tokenId: 10,
        name: "404 Billboard",
        image_url: "https://www.arweave.net/_5u97VpJgtmcKXFrJH5515HC8T0ooBYTQW-pxXXq3HQ?ext=png",
        json_url: "https://www.arweave.net/UXa9mokG0U6grG3IYe_TfAeHFlNZCsT_NOWNQJFzuw8",
        size: [1, 3, 3],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      11: {
        tokenId: 11,
        name: "Maintenance Logo",
        image_url: "https://www.arweave.net/ZpUwoVYGaNUuMcAqjQImzfSy2emZuGgnpZe6yVq9PGM?ext=png",
        json_url: "https://www.arweave.net/2Tl1LYe21GH31qgHquAFOy0Nq02RIbuqWHrddxbV8WA",
        size: [2, 4, 1],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
      },
      12: {
        tokenId: 12,
        name: "Red Tile",
        image_url: "https://www.arweave.net/iay99djnmU2y6gZkzvZK8VIqwiQztLX0JHavf8Jnrhw?ext=png",
        json_url: "https://www.arweave.net/Y1irv5iVi8fhznHyCvzyqGTfJlx_FbbwcVrHBUHX96s",
        size: [1, 1, 1],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
      },
      13: {
        tokenId: 13,
        name: "Blue Tile",
        image_url: "https://www.arweave.net/Fh-uhYCy1dqnLvuePl6ll5BLSzeC1ZtQmpJ72SCGFKg?ext=png",
        json_url: "https://www.arweave.net/_idZ2TV_XNxGAvPgtMr084dSN5BdPxG5w7zk2NTk23A",
        size: [1, 1, 1],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
      },
      14: {
        tokenId: 14,
        name: "Yellow Tile",
        image_url: "https://www.arweave.net/P0YHngzyz2TgNVUBx8bsCB8TSZMvuqpuJKavZ0ExJfY?ext=png",
        json_url: "https://www.arweave.net/Hamxsxz9-tkJc_R9_f7sLweQA645NTRDYrIRVeHvQd0",
        size: [1, 1, 1],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
      },
      15: {
        tokenId: 15,
        name: "Green Tile",
        image_url: "https://www.arweave.net/T7z7fOemLAW83oH6XbKKP2HSHhZdQhbSeDm0QDGX0tY?ext=png",
        json_url: "https://www.arweave.net/0gPIAptJgBnvfFydKIXcjw0DoQH__iOY-vI79QWoJ3A",
        size: [1, 1, 1],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
      },
      16: {
        tokenId: 16,
        name: "Black Tile",
        image_url: "https://www.arweave.net/jGd2fXsW524O0LVov8-qUYEuJpv_ILRY0f_9kXskwSE?ext=png",
        json_url: "https://www.arweave.net/BTcgKyik2zcsDOiJwnENcfxA4pDfgk61DBbjnc6T3DM",
        size: [1, 1, 1],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
      },
      17: {
        tokenId: 17,
        name: "White Tile",
        image_url: "https://www.arweave.net/AwLkA_WQDtYvFH5O90OCc_yVXfjXoLZsCrQyiyMcB6s?ext=png",
        json_url: "https://www.arweave.net/_aP7l5O__tMU77GJeeg5FOv3MJbUWFJWct3n36Lp5yM",
        size: [1, 1, 1],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 0,
      },
      18: {
        tokenId: 18,
        name: "Street Straight X",
        image_url: "https://www.arweave.net/7QmIjijitpeeAph9TsZrokF6fg2EhckQp2cb15uLSU4?ext=png",
        json_url: "https://www.arweave.net/ke8GOb7eE9OgqHYu_KrRKCE65ipNMxYfoa6XaBFVKlQ",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      19: {
        tokenId: 19,
        name: "Street Straight Y",
        image_url: "https://www.arweave.net/FLaUtCZMUqUzXJw6VWLUy-Xf6Ez03SZ_hSQEkN9t2co?ext=png",
        json_url: "https://www.arweave.net/yo5S6iQDOuPQdY067Ltpsw97LQYkbUaom6dc_qnyrWs",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      20: {
        tokenId: 20,
        name: "Street Crossing",
        image_url: "https://www.arweave.net/FUvk0BHbUbCs9qU-9EBRqlQrnZoGVYC5VNVR6aPCtoU?ext=png",
        json_url: "https://www.arweave.net/mF1LCfSngrPGeGhS1gutbTMDE7azXTu2GqI-oanKuo8",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      21: {
        tokenId: 21,
        name: "Street Corner Top",
        image_url: "https://www.arweave.net/3nBEZactbYo3PX2zk6ddeulGx98WqCJio48E4Tjj71k?ext=png",
        json_url: "https://www.arweave.net/8OFyEwoQ21Fq-1QazOklL9Snn-LKZRd1-yEX6RIFglw",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      22: {
        tokenId: 22,
        name: "Street Corner Right",
        image_url: "https://www.arweave.net/xEMpWzaWn113ueXNdGbmq0sIkzVUTUSJJL5jEvd6dRs?ext=png",
        json_url: "https://www.arweave.net/Jsl0ebWmS9gxsOTLqhHtM5WlU3mx_PmdCSSYFcqOAEw",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      23: {
        tokenId: 23,
        name: "Street Corner Left",
        image_url: "https://www.arweave.net/VFhM6E8FZMi6osY49O77F-pf42HpqRCVstplaCSzZEY?ext=png",
        json_url: "https://www.arweave.net/otzAFBpJv-aVvSE-UzV1oS04cN0hNbwD_nwnT02cCHI",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      24: {
        tokenId: 24,
        name: "Street Corner Bottom",
        image_url: "https://www.arweave.net/jSj8lIbj2Le34Tm0blmcJvK7U3XYf5RM6w1drS25bGM?ext=png",
        json_url: "https://www.arweave.net/aX34cgnGj8ikoT0T6mjxCsifmnBW1eZOlQj42Vy66sc",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      25: {
        tokenId: 25,
        name: "Street Crossing X",
        image_url: "https://www.arweave.net/T9YkNq6T-h5s6Ft3XeUVIoHpXyCzsIRBn4IGME9h2BE?ext=png",
        json_url: "https://www.arweave.net/k3EBxuUnDelct2v83a8hGWLecTC34Z2Y2FqAvHPMi1o",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      26: {
        tokenId: 26,
        name: "Street Crossing Y",
        image_url: "https://www.arweave.net/aRcuYEiBPjxLt8FjOuBbIKShN0k12sv84oJD8_TUcNM?ext=png",
        json_url: "https://www.arweave.net/ELfvO2Rt3SpIRRzVjuT2w2JW-VnqK7K9mn0rxnuZOL8",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      27: {
        tokenId: 27,
        name: "Street Phi Logo X",
        image_url: "https://www.arweave.net/3oBH87Gtzvqbn_PCzCa2LGAfT_zKTr7xdsR7tgOZzT0?ext=png",
        json_url: "https://www.arweave.net/XbnLJND_hwW5aW5RNQZysO-jkZl7Yupryq5uDYw55Ts",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      28: {
        tokenId: 28,
        name: "Street Phi Logo Y",
        image_url: "https://www.arweave.net/sUkGM0uumlUElUggpDRKSZWEHFGRKBMjh_qePIjp2io?ext=png",
        json_url: "https://www.arweave.net/djJL-J8m35yWuN7zAnKYJ73eiy4ppr_oLwtl21DVXjM",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      29: {
        tokenId: 29,
        name: "Street Blank",
        image_url: "https://www.arweave.net/1t9xqtc2xc75bKUCxZWcO3e3nAVhyfKhQQ4jKUiOEKs?ext=png",
        json_url: "https://www.arweave.net/7DgacR-IzdGAmUKgwQORLhLj0VZkyJuBrznTfA-4BUQ",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      30: {
        tokenId: 30,
        name: "Circuit Board Lawn",
        image_url: "https://www.arweave.net/jVC1tpbElJIReX_cokP103Ap2J354CXmhZ9151hgN88?ext=png",
        json_url: "https://www.arweave.net/Zc2uZQJ1PkEzvMFemTOewrn-NBKEKKdTg8nasbiaS4s",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      31: {
        tokenId: 31,
        name: "Circuit Board Tree 1",
        image_url: "https://www.arweave.net/UGTRs93U61-iqG21hzEJY8uy9V5FEP5cUvw0L6HQFtQ?ext=png",
        json_url: "https://www.arweave.net/tBGOWl9ipddyAsy8kBeov3sjBnLtGFiAmBYqH6N_uwg",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      32: {
        tokenId: 32,
        name: "Circuit Board Tree 2",
        image_url: "https://www.arweave.net/IvaVsJhQ95eNxaWHKDAV6K6wFV5F1ptronC804c_Cqo?ext=png",
        json_url: "https://www.arweave.net/qtCQUcHTAuCMxg0fODan8PJVZwGUCV-JlVi7SLOL-Qo",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      33: {
        tokenId: 33,
        name: "Circuit Board Tree 3",
        image_url: "https://www.arweave.net/pCkHaxPyWY87pLn00wX9YuP_UG039kfqQsLHGef1r_A?ext=png",
        json_url: "https://www.arweave.net/kq0WHkDyslmOzLew83Eotlt2d-63Rwbi4vYo7yE7hxA",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      34: {
        tokenId: 34,
        name: "Circuit Board Tree 4",
        image_url: "https://www.arweave.net/hnyNy9HsvD3-vzhbCLhvyGoEwybNQ7hzFxTdRp2MRIs?ext=png",
        json_url: "https://www.arweave.net/CkFG-5_0_09zIp1wh_ggmdobdGGxFV9DuF8zO_woqMM",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      35: {
        tokenId: 35,
        name: "Circuit Board Tree 5",
        image_url: "https://www.arweave.net/x0oY5I47JJokNZMVzl7r6UZZDcNNToJve1UQ4UfHVB0?ext=png",
        json_url: "https://www.arweave.net/xPYbNud6Q0euHm2mXNFOfb3t1oke_hrB7FVisT7AO_4",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      36: {
        tokenId: 36,
        name: "Dotty",
        image_url: "https://www.arweave.net/ZTC_-Ijhh6UjYFWgjdADfCgA1Jqsvue5OsFtoqv1kAc?ext=png",
        json_url: "https://www.arweave.net/RROpRF7SwKk13b7h-Nc3jWrz4V8qwLSVzJIJAT2iku4",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      37: {
        tokenId: 37,
        name: "Lawn Builder",
        image_url: "https://www.arweave.net/0FPcBfnk3jyaVHEyEKPKPHkB0kjx7WGYl4UcTBHPMhs?ext=png",
        json_url: "https://www.arweave.net/AX23NS2D8fF3hN2RiwZaFDdOafWbzBtjLia6Qs4Bi2w",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      38: {
        tokenId: 38,
        name: "HardHat Group 2",
        image_url: "https://www.arweave.net/aW9vEZ9xGk4zZtdEXLAeCM71dpStNW94GfL1lzdn4NU?ext=png",
        json_url: "https://www.arweave.net/Pxdz_BCsbOIzUDfVJ5W5X4ooKFntogjWi7Z8gO2ZEt4",
        size: [2, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      39: {
        tokenId: 39,
        name: "HardHat Group 3",
        image_url: "https://www.arweave.net/R68qlK-Fcg7XRjfJNyqn7qYMAS_KE-LfxDkVu5id3pI?ext=png",
        json_url: "https://www.arweave.net/TVrGFdvYVTGvYnfMpRgScEkbq_vI1_xuJQkoDfEP5nc",
        size: [2, 2, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      40: {
        tokenId: 40,
        name: "Street Painter Back",
        image_url: "https://www.arweave.net/LHX3jwrHm-u-m5Oxk_t0Buz5UWKU3wpPO0Siz8eLVqk?ext=png",
        json_url: "https://www.arweave.net/YB50K2WN4511MsBJKboqKgY3-4j2hzCPH0P0vftZvtM",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      41: {
        tokenId: 41,
        name: "Street Painter Front",
        image_url: "https://www.arweave.net/a0QzZ1q5hzZwwXHm0zIu54xVZsYBoRLi6TrEF67u_b8?ext=png",
        json_url: "https://www.arweave.net/ju8UgvE8atoSoL4NSDHorx6iU5fYS8ujvFPreDmRCTo",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      42: {
        tokenId: 42,
        name: "Street Painter Back Right",
        image_url: "https://www.arweave.net/BJjCdk3t_rtJ8JabgWBaGrlXyYZ0lwlnhJ-9pe0njKA?ext=png",
        json_url: "https://www.arweave.net/wvm3eFtL7It7SNn-k3WuoT9EL_MAXneL92m_uahw8fk",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      43: {
        tokenId: 43,
        name: "Street Painter Front Left",
        image_url: "https://www.arweave.net/s36Mr5gtTFrNutCAymkH9nLH236mM1h8YCU148I8GoA?ext=png",
        json_url: "https://www.arweave.net/-wlBbZi976G2tt2jB2SrtreCliVHNeS2-BNmnApzHhk",
        size: [1, 1, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
    },
    [PREMIUM_OBJECT_CONTRACT_ADDRESS]: {
      4: {
        tokenId: 4,
        name: "Phi TrafficSign 1",
        image_url: "https://www.arweave.net/nxA2Za1avhXvXcUSc2_7S3sSaUQs9UNoTaZUBZgToo8?ext=png",
        json_url: "https://www.arweave.net/B-uoml1C53BWQikZdpWCHh0wvfwa9O8jAzyiP4S2zYk",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 20,
      },
      5: {
        tokenId: 5,
        name: "Phi TrafficSign 2",
        image_url: "https://www.arweave.net/Mbzfc7ZW4jdz1j6CBQRj4hkdT_Rp5cHt4R1VL-N-5K8?ext=png",
        json_url: "https://www.arweave.net/K-GcUd3ec5vBgbKdwtOukVhYIwGYPkuHU2tpCjn-HE8",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 20,
      },
      6: {
        tokenId: 6,
        name: "Phi-Chopper EasyRider",
        image_url: "https://www.arweave.net/RWTQ16cJmz0HvaJU5-G-cn6OTkriYdg7gteDDJDTRlc?ext=png",
        json_url: "https://www.arweave.net/JYo_cfEu4RERBVj2hgB9Od2ZxcF9Bx2NMSpc2EZ843U",
        size: [1, 2, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 40,
      },
      7: {
        tokenId: 7,
        name: "Phi-Chopper StripesRider",
        image_url: "https://www.arweave.net/O6GXFRPPrtqIDtijw5QQkF7kaTEtMBYVnilzwK6UB8o?ext=png",
        json_url: "https://www.arweave.net/azqeSHKcxG-ktwbt7T0EZesVmOpvbSp4ek6fiDirGw4",
        size: [1, 2, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 40,
      },
      8: {
        tokenId: 8,
        name: "Phi-Chopper DirtRider",
        image_url: "https://www.arweave.net/vp-DeStQTrEYS5M9uxsGLiF7S63RIKT2p2L6dTgdgaU?ext=png",
        json_url: "https://www.arweave.net/Zy2rAOqavj1usn0Tl3cjZEULw01PPX9z9Ww4aO9ygLA",
        size: [1, 2, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 40,
      },
      10: {
        tokenId: 10,
        name: "Buy Sign",
        image_url: "https://www.arweave.net/QRKDHgAweb0xwOZs2biOJE_NMq6h-k2So7iCQy_TaSc?ext=png",
        json_url: "https://www.arweave.net/roatFQcSlbK2xG_K9HazHwowy6dzOaIcgzu9Gx20SjQ",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 20,
      },
      11: {
        tokenId: 11,
        name: "Sell Sign",
        image_url: "https://www.arweave.net/MsEvPZIdzg4lT7xDYbOTGdOh9KH-xWZtZ8FJAHGLvFM?ext=png",
        json_url: "https://www.arweave.net/cg3_f-uIOYWd56YDxPDnUoJrifeBK4BCfW32uwOYTyQ",
        size: [1, 1, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 20,
      },
      13: {
        tokenId: 13,
        name: "Piggy Bank Pink",
        image_url: "https://www.arweave.net/84JttX_6gUlMCBUF1U1yVbVwKAwlOcq-Hb-K8odW7g8?ext=png",
        json_url: "https://www.arweave.net/-VyIjYmEkcJI3lHg2kC5E0PifprrUgOX3QMeAwUY4CA",
        size: [1, 2, 1],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 60,
      },
      19: {
        tokenId: 19,
        name: "Bitcoin Chess Piece",
        image_url: "https://www.arweave.net/0QLkTyXk7r3olkbY3OndjU_wOy7LDvrkyltl8XklYgE?ext=png",
        json_url: "https://www.arweave.net/DIC_LjfXDvoIXDo8BssDt-ZX3Jo-QnQIXQYrCR86p_c",
        size: [3, 2, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 20,
      },
      20: {
        tokenId: 20,
        name: "Tezos Chess Piece",
        image_url: "https://www.arweave.net/2eNPGg7V3eyDPPhy9ATAdd5rWuulyskK64ixKfKKez4?ext=png",
        json_url: "https://www.arweave.net/kafByUuq7vbxm-q-xXZ_s2eUhrs4v4XHT7CqUvS8N_s",
        size: [3, 2, 2],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 20,
      },
      22: {
        tokenId: 22,
        name: "PHI Shrub",
        image_url: "https://www.arweave.net/4r3L7KYO6C5bjSJrAHOdHcYjhBj3dpFEeVCyCMhZjro?ext=png",
        json_url: "https://www.arweave.net/tSXzSnriqDZVeXKvJGqXdXM9QxcPH_mD8iWWHE8tHSU",
        size: [3, 2, 2],
        creator: "ta2nb",
        maxClaimed: 999999999,
        price: 20,
      },
    },
    [WALLPAPER_CONTRACT_ADDRESS]: {
      1: {
        tokenId: 1,
        name: "Default",
        image_url: "https://www.arweave.net/A4Zg4LGVMSMri9ypkRSG9zF_AhmIwOvuJfHIC_KXWTg?ext=png",
        json_url: "https://www.arweave.net/NwB7NqrkmbeW96F9cJKKZY4DVbjrluSWe_W1fNPy484",
        size: [16, 16],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      2: {
        tokenId: 2,
        name: "Cali",
        image_url: "https://www.arweave.net/eTRzk6NYBoYxW6Z4woOo0_NAlUC4KkjKIxAWua72PrQ?ext=png",
        json_url: "https://www.arweave.net/8o-wx6UNmfMXRyTOl3AOJScCahhepQ4oSL9NIxi0sAg",
        size: [16, 16],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      3: {
        tokenId: 3,
        name: "Checkerscali",
        image_url: "https://www.arweave.net/rmr9ubFZayxSrGrEjvd-vgpGzOXsIi-PAIezU7NhAFg?ext=png",
        json_url: "https://www.arweave.net/rz2ldHOqCCl6dxCtORTXNYT7CMA-8IF_MXHUblvQaNU",
        size: [16, 16],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      4: {
        tokenId: 4,
        name: "Crossdirt",
        image_url: "https://www.arweave.net/tiHKCbRqhYcClB-6U9XXdslsUrZJxpkgalRkvIzIaq8?ext=png",
        json_url: "https://www.arweave.net/PMTNxss9Sy8qIy59eEqiDrmD5IcVFnL8dWjxuV7g5rs",
        size: [16, 16],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      14: {
        tokenId: 14,
        name: "Logoisoisospaced",
        image_url: "https://www.arweave.net/2-g-SmCzF2Me6P76dcfj7Yt61qNtmKw7tipgZtJk8sc?ext=png",
        json_url: "https://www.arweave.net/QrfBRXzphQ9Q2SkycNNCdoPeapxDX7L8oBl1SpsDbvc",
        size: [16, 16],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
      15: {
        tokenId: 15,
        name: "Logoisoisospacedorig",
        image_url: "https://www.arweave.net/795dKnnyQ0g8oVUmITtJnTHJ_u4xBa8coBGXaXr2zCE?ext=png",
        json_url: "https://www.arweave.net/spBs3wBEW8D1D87LKTiVzzQm7EvkeBw94H1UJfWRhJs",
        size: [16, 16],
        creator: "eBoy",
        maxClaimed: 999999999,
        price: 0,
      },
    },
  };

export type ObjectTraits = {
  attributes: { trait_type: string; value: string }[];
  name: string;
  description: string;
  collection: {
    family: string;
    name: string;
  };
};

export let objectTraisList: { [contract in ObjectContractAddress | WallpaperContractAddress]: { [tokenId: number]: ObjectTraits } } = {
  [QUEST_OBJECT_CONTRACT_ADDRESS]: {},
  [FREE_OBJECT_CONTRACT_ADDRESS]: {},
  [PREMIUM_OBJECT_CONTRACT_ADDRESS]: {},
  [WALLPAPER_CONTRACT_ADDRESS]: {},
};

const setTraits = () => {
  Promise.all(
    Object.keys(objectMetadataList).map((key) => {
      const contract = key as ObjectContractAddress | WallpaperContractAddress;
      Object.values(objectMetadataList[contract]).map(async (meta) => {
        const res = await axios.get<ObjectTraits>(meta.json_url);
        objectTraisList = {
          ...objectTraisList,
          [key]: {
            ...objectTraisList[contract],
            [meta.tokenId]: res.data,
          },
        };
      });
    })
  );
};
setTraits();
